version: "3"

services:
  release:
    image: tons/whoami:${TAG:-latest}
    build: .
    ports:
      - 8080:8080
    environment:
      JAVA_OPTS: -Xmx512M -Xms256M

  test:
    image: openjdk:8-jdk-alpine
    working_dir: /src
    volumes:
    - .:/src
    command: ./gradlew clean test
