version: "3"

services:
  release:
    image: tons/whoami:${TAG}
    build: .
    ports:
      - 8080:8080

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
      - ${DEBUG_PORT:-5005}:${DEBUG_PORT:-5005}
    environment:
     - DEBUG_PORT=${DEBUG_PORT:-5005}
