version: 2
jobs:
  build:
    docker:
      - image: tons/dc-ci
    steps:
      - setup_remote_docker
      - checkout
      - run: TAG=ci exec /ci/build-push.sh
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
